### ISSUE TITLE
Confused about `intervalChunk` within `accessDMDAnn.py`

### ISSUE THREAD

**Issue by YIMINGMA** [Vicomtech/DMD-Driver-Monitoring-Dataset#2]
Hello Vicromtech,

I am confused about `intervalChunk` within `accessDMDAnn.py`. May I ask how it is related to splitting videos to frames? If I'd like to divide a sec of video clip into 10 images (10 frames per second), how shall I set this value? Or do you have any suggested value for it? The default value `0` results in a really large dataset.

Many thanks,
Yiming

**Comment by pncanas333** [comment]
Hello @YIMINGMA 

The interval Chunk var specifies the length (in frames) of the resulting videoclips after cutting the entire video. So, if a have a video of 30 frames and the intervalChunk is 10, then it will result in 3 videoclips (each with 10 frames). The default value is 0, meaning that you don't want to cut the video into subclips.

In your case, you want a second of video (30 frames) into 10 images (or frames), so you need to delete 20 images (or frames). That's not possible with any configuration right now. I suggest you cut videos by 30 frames (intervalChunk=30) and then, with posterior processing (maybe with ffmpeg or numpy), you can equitably discard or drop 20 frames from each subclip, so you have 10 frames per second of video. 

Hope I made myself clear.

**Comment by YIMINGMA** [comment]
Hi @pncanas333 Paola,

Your explanation is very clear and detailed. Thank you for your help. The DMD data set is indeed very rich in details, and users do have the freedom to create their own versions. I really appreciate the contribution from Vicomtech.

Many thanks,
Yiming
