### ISSUE TITLE
Spatial annotations

### ISSUE THREAD

**Issue by yongyuandeyezi** [Vicomtech/DMD-Driver-Monitoring-Dataset#4]
Is Tato only for temporal annotations? How can I do Spatial annotations, such as body landmarks, face landmarks?

**Comment by pncanas333** [comment]
Yes, TaTo (Temporal Annotation Tool) is only for temporal annotations. 
There are other free (and online) annotation tools for spatial annotations on the internet. Also, you can get spatial annotations by running landmarks detection models.
