### ISSUE TITLE
Failed to extract depth images

### ISSUE THREAD

**Issue by jhan15** [Vicomtech/DMD-Driver-Monitoring-Dataset#6]
Hello,

I'm trying to extract the images with the DExTool.py. I successfully extracted the rgb and ir channels. However, I cannot extract the depth images. It seems when reading depth frames, it just stopped at a certain frame. There's no image in the destination depth folder.

I'm using ubuntu 18.04

The output in the terminal:

-- Getting data of depth channel --

-- Creating image of action: gaze_on_road/looking_road --
depth face stream loaded: gA_1_s1_2019-03-08T09;31;15+01;00_depth_face.avi
Writing...
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, avi, from '/home/han/Documents/DMD-Driver-Monitoring-Dataset/dmd/gA/1/s1/gA_1_s1_2019-03-08T09;31;15+01;00_depth_face.avi':
  Metadata:
    encoder         : Lavf57.83.100
  Duration: 00:03:47.72, start: 0.000000, bitrate: 51569 kb/s
    Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), gray16le, 1280x720, 51570 kb/s, 29.76 fps, 29.76 tbr, 29.76 tbn, 29.76 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (ffv1 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to 'pipe:':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: rawvideo (Y1[0][16] / 0x10003159), gray16le, 1280x720, q=2-31, 438829 kb/s, 29.76 fps, 29.76 tbn, 29.76 tbc
    Metadata:
      encoder         : Lavc57.107.100 rawvideo
frame=   57 fps=0.0 q=-0.0 size=  102600kB time=00:00:01.91 bitrate=438829.
frame=  119 fps=118 q=-0.0 size=  214200kB time=00:00:03.99 bitrate=438829.
......
frame= 4249 fps=100 q=-0.0 size= 7648200kB time=00:02:22.77 bitrate=438829.
frame= 4257 fps= 99 q=-0.0 size= 7662600kB time=00:02:23.04 bitrate=438829.
Killed/s speed=3.31x

**Comment by pncanas333** [comment]
Hello @jhan15 
I've tried to reproduce this error without success. I don't know what could be happening. 

Is this still occurring? This happens with other videos too? Maybe you have 'write permission' issues? (maybe not since you can export other channels)
I also would say to try with different versions of FFMPEG or update it, but this doesn't seem to be the problem unless there is a library to support FFV1 format that is not installed and is not creating the images

**Comment by pncanas333** [comment]
#5 Maybe trying on another computer? hehe
