### ISSUE TITLE
What do the fields in JSON mean

### ISSUE THREAD

**Issue by Programmerwyl** [Vicomtech/DMD-Driver-Monitoring-Dataset#7]
"vcd": {
    "frames": {
      "0": {
        "objects": {
          "0": {
            
          }
        },
        "contexts": {
          "0": {
            
          }
        },
        "actions": {
          "0": {
            "action_data": {
              "text": [
                {
                  "name": "annotated",
                  "val": "unchanged"
                }
              ]
            }
          }
        }
      },
      "1": {
        "objects": {
          "0": {
            
          }
        },
        "contexts": {
          "0": {
            
          }
        },
        "actions": {
          "0": {
            "action_data": {
              "text": [
                {
                  "name": "annotated",
                  "val": "unchanged"
                }
              ]
            }
          }
        }
      },

I  want to know what each field represnets ,like  "object " ,"contexts  “，”actions “？

how to express the current state of the driver, is is 0,1,2?  how do the numbers correspond ?

thanks

[gA_1_s1_2019-03-08T09;31;15+01;00_rgb_ann_distraction.zip](https://github.com/Vicomtech/DMD-Driver-Monitoring-Dataset/files/8367511/gA_1_s1_2019-03-08T09.31.15%2B01.00_rgb_ann_distraction.zip)

**Comment by pncanas333** [comment]
Hello @Programmerwyl 

Annotations come in VCD format. You can get to know this format better on its [website](https://vcd.vicomtech.org/). 
There is a complex definition for Driver distraction-related annotations. You can understand it better on the [wiki](https://github.com/Vicomtech/DMD-Driver-Monitoring-Dataset/wiki/DMD-distraction-related-action-annotation-criteria).
Also, there's more information in the [distraction config file](annotation-tool/config_distraction.json). 

I suggest that you use [DExTool](https://github.com/Vicomtech/DMD-Driver-Monitoring-Dataset/tree/master/exploreMaterial-tool) to prepare data for training. This tool can access the JSON file and extract the material of the classes you wish. 

The piece of the JSON file you sent corresponds to a "frame" view. For frame "0", there are "Objects" (0), "Actions"(0) and "Contexts"(0). For frame "1", the same. 

In the VCD, each "action" (label of distraction) has an ID assigned (automatically, so there is no clear correspondence) in the example you sent, "0" is safe driving. This means that for frames 0 and 1, the driver was performing the safe driving activity. 

You can know what label each action corresponds with by checking the action name. Take the "action" id and go to the "actions" object and look for that id.

**Comment by Programmerwyl** [comment]
Hi @pncanas333 

Thanks for your reply.

Now that, I know how to look at this json file.
thanks
